# action name
name: "Chromatic"
# the event that triggers the action
on: push

# what the action will do
jobs:
  test:
    # the os it will run
    runs-on: ubuntu-latest
    # the list of steps that the action will go thru
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        # options required to the GitHub chromatic action
        with:
          projectToken: project-token
          token: ${{ serets.GITHUB_TOKEN }}
